from django.urls import path, include
from rest_framework import routers
from product.viewsets.category_viewset import CategoryViewSet
from product.viewsets.product_viewset import ProductViewSet

# Create a router object to automatically generate URLs for viewsets
router = routers.SimpleRouter()

# Register the ProductViewSet with the router, making its routes available under the 'products' path
router.register(r'products', ProductViewSet, basename='product')

# Register the CategoryViewSet with the router, making its routes available under the 'categories' path
router.register(r'categories', CategoryViewSet, basename='category')

# Define the URL patterns for this app
urlpatterns = [
    path('', include(router.urls)),  # Include the URLs generated by the router
]
